version: '3.5'
services:
  database:
    image: postgres:latest
    command: postgres -c 'max_connections=450'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=rinha_backend
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.85'
          memory: '1.9GB'

  api1:
    # image: oliveigah/rinha-backend:finalv2
    build: .
    depends_on:
      - database
    network_mode: host
    environment:
      HTTP_SERVER_PORT: 3000
      RELEASE_COOKIE: "secret_cookie"
      RELEASE_NODE: "api1@localhost"
      RELEASE_DISTRIBUTION: "sname"
      BOOTSTRAP_NODES: "api2@localhost"
      DB_CONNS: 160
    healthcheck:
      test: curl -f http://localhost:3000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.4GB'

  api2:
    # image: oliveigah/rinha-backend:finalv2
    build: .
    depends_on:
      - api1
    network_mode: host
    environment:
      ERL_MAX_PORTS: 2048
      HTTP_SERVER_PORT: 3001
      RELEASE_COOKIE: "secret_cookie"
      RELEASE_NODE: "api2@localhost"
      RELEASE_DISTRIBUTION: "sname"
      BOOTSTRAP_NODES: "api1@localhost"
      DB_CONNS: 160
    healthcheck:
      test: curl -f http://localhost:3001
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.4GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

volumes:
  database:
